# Diabetes Analysis
## Group 1

**1. Data Loading and Filtering**

In [2]:
import numpy as np
import os
import pandas as pd

# to make this notebook's output stable across runs
np.random.seed(42)

Data Loading

In [3]:
df_raw = pd.read_csv('brfss_2019_2025_combined.csv')
print("Data Raw shape:", df_raw.shape)
print("Data Raw columns:", df_raw.columns.tolist())
df_raw

Data Raw shape: (2951202, 31)
Data Raw columns: ['_STATE', 'IYEAR', 'GENHLTH', 'PHYSHLTH', 'MENTHLTH', '_HLTHPL2', 'PERSDOC3', 'MEDCOST1', 'CHECKUP1', 'CVDSTRK3', 'ADDEPEV3', 'CHCKDNY2', 'DIABETE4', 'HAVARTH4', 'MARITAL', 'EDUCA', 'RENTHOM1', 'VETERAN3', 'EMPLOY1', 'INCOME3', 'DIFFWALK', 'SMOKE100', 'ALCDAY4', '_URBSTAT', '_MICHD', '_RACE', '_SEX', '_AGEG5YR', '_BMI5', '_RFDRHV9', '_TOTINDA']

,_STATE,IYEAR,GENHLTH,PHYSHLTH,MENTHLTH,_HLTHPL2,PERSDOC3,MEDCOST1,CHECKUP1,CVDSTRK3,...,SMOKE100,ALCDAY4,_URBSTAT,_MICHD,_RACE,_SEX,_AGEG5YR,_BMI5,_RFDRHV9,_TOTINDA
0,1.0,2019,3.0,15.0,88.0,1.0,1.0,2.0,1.0,2.0,...,1.0,888.0,1.0,2.0,2.0,2.0,13.0,2817.0,1.0,2.0
1,1.0,2019,4.0,10.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,1.0,2.0,1.0,2.0,11.0,1854.0,1.0,1.0
2,1.0,2019,3.0,88.0,30.0,1.0,2.0,2.0,1.0,2.0,...,2.0,888.0,1.0,2.0,2.0,2.0,10.0,3162.0,1.0,1.0
3,1.0,2019,4.0,30.0,88.0,1.0,1.0,2.0,1.0,2.0,...,NaN,NaN,1.0,2.0,1.0,2.0,13.0,2030.0,9.0,9.0
4,1.0,2019,2.0,88.0,88.0,1.0,1.0,2.0,1.0,2.0,...,1.0,888.0,2.0,2.0,1.0,2.0,13.0,2148.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2951197,72.0,2026,4.0,30.0,88.0,1.0,2.0,2.0,1.0,2.0,...,1.0,888.0,NaN,1.0,8.0,2.0,11.0,2663.0,1.0,2.0
2951198,72.0,2026,2.0,88.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,NaN,2.0,8.0,2.0,10.0,2661.0,1.0,1.0
2951199,72.0,2026,1.0,1.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,NaN,2.0,8.0,2.0,8.0,2480.0,1.0,1.0
2951200,72.0,2026,5.0,30.0,30.0,1.0,1.0,2.0,1.0,2.0,...,1.0,888.0,NaN,2.0,8.0,2.0,14.0,3987.0,1.0,1.0
2951201,72.0,2026,2.0,88.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,NaN,2.0,8.0,1.0,5.0,2009.0,1.0,1.0

Data Type and Exploratory

In [4]:
print("===Data Types===")
print(df_raw.dtypes)

===Data Types===
_STATE      float64
IYEAR         int64
GENHLTH     float64
PHYSHLTH    float64
MENTHLTH    float64
_HLTHPL2    float64
PERSDOC3    float64
MEDCOST1    float64
CHECKUP1    float64
CVDSTRK3    float64
ADDEPEV3    float64
CHCKDNY2    float64
DIABETE4    float64
HAVARTH4    float64
MARITAL     float64
EDUCA       float64
RENTHOM1    float64
VETERAN3    float64
EMPLOY1     float64
INCOME3     float64
DIFFWALK    float64
SMOKE100    float64
ALCDAY4     float64
_URBSTAT    float64
_MICHD      float64
_RACE       float64
_SEX        float64
_AGEG5YR    float64
_BMI5       float64
_RFDRHV9    float64
_TOTINDA    float64
dtype: object

Age group counts

In [ ]:
# Map BRFSS age-group codes to readable labels
age_labels = {
    1: "18-24",
    2: "25-29",
    3: "30-34",
    4: "35-39",
    5: "40-44",
    6: "45-49",
    7: "50-54",
    8: "55-59",
    9: "60-64",
    10: "65-69",
    11: "70-74",
    12: "75-79",
    13: "80+",
    14: "Don't know/Refused",
}

# Count rows in each age group, including missing values as separate category
age_counts = (
    df_raw["_AGEG5YR"]
    .astype("Int64")
    .value_counts(dropna=False)
    .reindex(range(1, 15), fill_value=0)
    .rename(index=age_labels)
)

print("Age group counts for _AGEG5YR:")
print(age_counts)

print("Hello")

Age group counts for _AGEG5YR:
_AGEG5YR
18-24                 182920
25-29                 148296
30-34                 168362
35-39                 184702
40-44                 191711
45-49                 187483
50-54                 216731
55-59                 245113
60-64                 292363
65-69                 310546
70-74                 289888
75-79                 221056
80+                   255629
Don't know/Refused     56402
Name: count, dtype: Int64

In [7]:
print("\n===Missing Values for the entire dataset===")
print(df_raw.isnull().sum())

# Overall missing-value percentage in the 18-29 age group
overall_null_pct = df_raw.isnull().mean().mean() * 100
print(f"Overall missing-value rate in the entire dataset: {overall_null_pct:.2f}%")

# Per-column missing-value percentage
null_pct_by_col = (df_raw.isnull().mean() * 100).sort_values(ascending=False)
print("\nMissing-value percentage by column for the entire dataset:")
print(null_pct_by_col)

===Missing Values for the entire dataset===
_STATE           0
IYEAR            0
GENHLTH         55
PHYSHLTH        56
MENTHLTH        37
_HLTHPL2        12
PERSDOC3        21
MEDCOST1        29
CHECKUP1        26
CVDSTRK3        28
ADDEPEV3        37
CHCKDNY2        34
DIABETE4        36
HAVARTH4        33
MARITAL         95
EDUCA           69
RENTHOM1        81
VETERAN3     11941
EMPLOY1      24529
INCOME3      60500
DIFFWALK    118557
SMOKE100    153648
ALCDAY4     192652
_URBSTAT     60960
_MICHD       31356
_RACE           95
_SEX             0
_AGEG5YR         0
_BMI5       289352
_RFDRHV9         0
_TOTINDA         0
dtype: int64
Overall missing-value rate in the entire dataset: 1.03%

Missing-value percentage by column for the entire dataset:
_BMI5       9.804547
ALCDAY4     6.527916
SMOKE100    5.206285
DIFFWALK    4.017244
_URBSTAT    2.065599
INCOME3     2.050012
_MICHD      1.062482
EMPLOY1     0.831153
VETERAN3    0.404615
_RACE       0.003219
MARITAL     0.003219
RENTHOM1    0.002745
EDUCA       0.002338
PHYSHLTH    0.001898
GENHLTH     0.001864
MENTHLTH    0.001254
ADDEPEV3    0.001254
DIABETE4    0.001220
CHCKDNY2    0.001152
HAVARTH4    0.001118
MEDCOST1    0.000983
CVDSTRK3    0.000949
CHECKUP1    0.000881
PERSDOC3    0.000712
_HLTHPL2    0.000407
IYEAR       0.000000
_STATE      0.000000
_SEX        0.000000
_AGEG5YR    0.000000
_RFDRHV9    0.000000
_TOTINDA    0.000000
dtype: float64

Filter to age group 18 to 29

In [5]:
df_18_29 = df_raw[df_raw["_AGEG5YR"].isin([1, 2])].copy()
df_18_29

,_STATE,IYEAR,GENHLTH,PHYSHLTH,MENTHLTH,_HLTHPL2,PERSDOC3,MEDCOST1,CHECKUP1,CVDSTRK3,...,SMOKE100,ALCDAY4,_URBSTAT,_MICHD,_RACE,_SEX,_AGEG5YR,_BMI5,_RFDRHV9,_TOTINDA
60,1.0,2019,1.0,88.0,88.0,2.0,3.0,2.0,1.0,2.0,...,2.0,888.0,1.0,2.0,2.0,2.0,1.0,2534.0,1.0,1.0
388,1.0,2019,3.0,88.0,30.0,1.0,3.0,2.0,1.0,2.0,...,1.0,888.0,1.0,2.0,1.0,2.0,2.0,2941.0,1.0,1.0
391,1.0,2019,2.0,88.0,20.0,2.0,1.0,1.0,2.0,2.0,...,2.0,212.0,1.0,2.0,2.0,2.0,2.0,2114.0,1.0,1.0
612,1.0,2019,2.0,88.0,88.0,1.0,3.0,2.0,1.0,2.0,...,2.0,777.0,2.0,2.0,2.0,1.0,1.0,2215.0,9.0,1.0
745,1.0,2019,3.0,2.0,88.0,1.0,3.0,1.0,1.0,2.0,...,1.0,888.0,1.0,2.0,1.0,2.0,2.0,2480.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2951168,72.0,2026,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,...,2.0,210.0,NaN,2.0,8.0,1.0,1.0,2111.0,1.0,2.0
2951183,72.0,2026,1.0,88.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,NaN,2.0,8.0,1.0,2.0,NaN,1.0,2.0
2951187,72.0,2026,2.0,88.0,14.0,1.0,1.0,2.0,1.0,2.0,...,2.0,203.0,NaN,2.0,8.0,1.0,1.0,2529.0,1.0,1.0
2951188,72.0,2026,2.0,88.0,10.0,1.0,3.0,2.0,3.0,2.0,...,2.0,203.0,NaN,2.0,8.0,2.0,1.0,3328.0,1.0,2.0
2951192,72.0,2026,1.0,88.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,202.0,NaN,2.0,1.0,2.0,1.0,2456.0,1.0,2.0

Filter to age group 55-64

In [6]:
df_55_64 = df_raw[df_raw["_AGEG5YR"].isin([8, 9])].copy()
df_55_64

,_STATE,IYEAR,GENHLTH,PHYSHLTH,MENTHLTH,_HLTHPL2,PERSDOC3,MEDCOST1,CHECKUP1,CVDSTRK3,...,SMOKE100,ALCDAY4,_URBSTAT,_MICHD,_RACE,_SEX,_AGEG5YR,_BMI5,_RFDRHV9,_TOTINDA
11,1.0,2019,5.0,30.0,88.0,1.0,1.0,2.0,1.0,2.0,...,1.0,888.0,1.0,2.0,3.0,1.0,8.0,2311.0,1.0,2.0
17,1.0,2019,7.0,88.0,88.0,2.0,3.0,1.0,2.0,2.0,...,1.0,888.0,1.0,2.0,1.0,1.0,9.0,2511.0,1.0,1.0
29,1.0,2019,3.0,88.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,1.0,2.0,2.0,2.0,8.0,2413.0,1.0,1.0
30,1.0,2019,2.0,88.0,15.0,1.0,1.0,2.0,1.0,2.0,...,1.0,230.0,1.0,2.0,1.0,2.0,9.0,2998.0,2.0,2.0
38,1.0,2019,5.0,30.0,30.0,1.0,1.0,2.0,1.0,2.0,...,1.0,888.0,2.0,2.0,1.0,1.0,8.0,4068.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2951162,72.0,2026,3.0,88.0,88.0,1.0,3.0,2.0,3.0,2.0,...,2.0,103.0,NaN,2.0,8.0,1.0,8.0,3258.0,2.0,1.0
2951193,72.0,2026,4.0,88.0,4.0,1.0,1.0,2.0,3.0,2.0,...,2.0,204.0,NaN,2.0,8.0,1.0,9.0,2834.0,2.0,2.0
2951194,72.0,2026,1.0,88.0,88.0,1.0,1.0,2.0,1.0,2.0,...,1.0,888.0,NaN,2.0,8.0,1.0,9.0,2970.0,1.0,1.0
2951196,72.0,2026,4.0,30.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,NaN,2.0,8.0,2.0,8.0,3667.0,1.0,2.0
2951199,72.0,2026,1.0,1.0,88.0,1.0,1.0,2.0,1.0,2.0,...,2.0,888.0,NaN,2.0,8.0,2.0,8.0,2480.0,1.0,1.0

Count Missing Values

In [7]:
print("\n===Missing Values for 18-29 Age Group===")
print(df_18_29.isnull().sum())

===Missing Values for 18-29 Age Group===
_STATE          0
IYEAR           0
GENHLTH         6
PHYSHLTH        3
MENTHLTH        1
_HLTHPL2        1
PERSDOC3        0
MEDCOST1        2
CHECKUP1        0
CVDSTRK3        0
ADDEPEV3        1
CHCKDNY2        1
DIABETE4        0
HAVARTH4        1
MARITAL         3
EDUCA           2
RENTHOM1        3
VETERAN3     1523
EMPLOY1      3512
INCOME3      8292
DIFFWALK    14932
SMOKE100    17774
ALCDAY4     21957
_URBSTAT     7992
_MICHD       1891
_RACE           5
_SEX            0
_AGEG5YR        0
_BMI5       34946
_RFDRHV9        0
_TOTINDA        0
dtype: int64

In [8]:

# Overall missing-value percentage in the 18-29 age group
overall_null_pct_18_29 = df_18_29.isnull().mean().mean() * 100
print(f"Overall missing-value rate in age group 18-29: {overall_null_pct_18_29:.2f}%")

# Per-column missing-value percentage
null_pct_by_col_18_29 = (df_18_29.isnull().mean() * 100).sort_values(ascending=False)
print("\nMissing-value percentage by column for age group 18-29:")
print(null_pct_by_col_18_29)

Overall missing-value rate in age group 18-29: 1.10%

Missing-value percentage by column for age group 18-29:
_BMI5       10.550819
ALCDAY4      6.629209
SMOKE100     5.366287
DIFFWALK     4.508236
INCOME3      2.503502
_URBSTAT     2.412927
EMPLOY1      1.060335
_MICHD       0.570927
VETERAN3     0.459821
GENHLTH      0.001812
_RACE        0.001510
PHYSHLTH     0.000906
RENTHOM1     0.000906
MARITAL      0.000906
MEDCOST1     0.000604
EDUCA        0.000604
MENTHLTH     0.000302
CHCKDNY2     0.000302
_HLTHPL2     0.000302
ADDEPEV3     0.000302
HAVARTH4     0.000302
IYEAR        0.000000
_STATE       0.000000
DIABETE4     0.000000
CVDSTRK3     0.000000
CHECKUP1     0.000000
PERSDOC3     0.000000
_SEX         0.000000
_AGEG5YR     0.000000
_RFDRHV9     0.000000
_TOTINDA     0.000000
dtype: float64

In [9]:
print("\n===Missing Values for 55-64 Age Group===")
print(df_55_64.isnull().sum())

===Missing Values for 55-64 Age Group===
_STATE          0
IYEAR           0
GENHLTH         6
PHYSHLTH        5
MENTHLTH        3
_HLTHPL2        1
PERSDOC3        1
MEDCOST1        1
CHECKUP1        1
CVDSTRK3        2
ADDEPEV3        3
CHCKDNY2        1
DIABETE4        0
HAVARTH4        0
MARITAL         8
EDUCA           5
RENTHOM1        5
VETERAN3     2017
EMPLOY1      4051
INCOME3     10108
DIFFWALK    20052
SMOKE100    26567
ALCDAY4     33445
_URBSTAT    11999
_MICHD       4873
_RACE          10
_SEX            0
_AGEG5YR        0
_BMI5       46750
_RFDRHV9        0
_TOTINDA        0
dtype: int64

In [10]:
# Overall missing-value percentage in the 55-64 age group
overall_null_pct_55_64 = df_55_64.isnull().mean().mean() * 100
print(f"Overall missing-value rate in age group 55-64: {overall_null_pct_55_64:.2f}%")

# Per-column missing-value percentage
null_pct_by_col_55_64 = (df_55_64.isnull().mean() * 100).sort_values(ascending=False)
print("\nMissing-value percentage by column for age group 55-64:")
print(null_pct_by_col_55_64)

Overall missing-value rate in age group 55-64: 0.96%

Missing-value percentage by column for age group 55-64:
_BMI5       8.698063
ALCDAY4     6.222603
SMOKE100    4.942918
DIFFWALK    3.730771
_URBSTAT    2.232472
INCOME3     1.880642
_MICHD      0.906645
EMPLOY1     0.753708
VETERAN3    0.375273
_RACE       0.001861
MARITAL     0.001488
GENHLTH     0.001116
RENTHOM1    0.000930
EDUCA       0.000930
PHYSHLTH    0.000930
MENTHLTH    0.000558
ADDEPEV3    0.000558
CVDSTRK3    0.000372
_HLTHPL2    0.000186
CHECKUP1    0.000186
PERSDOC3    0.000186
CHCKDNY2    0.000186
MEDCOST1    0.000186
HAVARTH4    0.000000
DIABETE4    0.000000
IYEAR       0.000000
_STATE      0.000000
_SEX        0.000000
_AGEG5YR    0.000000
_RFDRHV9    0.000000
_TOTINDA    0.000000
dtype: float64

**2. Data Preprocessing**

In [11]:
df_18_29.to_csv("df_18_29.csv", index=False)

PermissionError: [Errno 13] Permission denied: 'df_18_29.csv'